include_guard(GLOBAL)

cmcm_module(Colors.cmake LOCAL modules/Colors.cmake VERSION 1)
cmcm_module(Messages.cmake LOCAL modules/Messages.cmake VERSION 1)
cmcm_module(Standards.cmake LOCAL modules/Standards.cmake VERSION 1)
cmcm_module(PreventInSourceBuilds.cmake LOCAL modules/PreventInSourceBuilds.cmake VERSION 1)
cmcm_module(DefaultInstallPrefix.cmake LOCAL modules/DefaultInstallPrefix.cmake VERSION 1)
cmcm_module(Doctest.cmake LOCAL modules/Doctest.cmake VERSION 1)
cmcm_module(Testings.cmake LOCAL modules/Testings.cmake VERSION 1)
cmcm_module(CPM.cmake LOCAL modules/CPM.cmake VERSION 1)
cmcm_module(Ping.cmake LOCAL modules/Ping.cmake VERSION 1)
cmcm_module(CLI11.cmake LOCAL modules/CLI11.cmake VERSION 1)
cmcm_module(PreCommit.cmake REMOTE https://raw.githubusercontent.com/flagarde/PreCommit/main/PreCommit.cmake VERSION 1)
